#!/bin/bash

# Pedir los datos al usuario
read -p "Introduce la IP (ej. 192.168.1.50): " IP
read -p "Introduce la máscara (ej. 24): " MASK
read -p "Introduce la puerta de enlace (Gateway, ej. 192.168.1.1): " GW
read -p "Introduce el DNS (ej. 8.8.8.8): " DNS

# Interfaz (cámbiala si sabes el nombre exacto)
IFACE="enp0s3"

# Reescribir el archivo YAML de Netplan desde cero
sudo tee /etc/netplan/50-cloud-init.yaml  > /dev/null <<EOF
network:
  ethernets:
    $IFACE:
      dhcp4: no
      addresses:
        - $IP/$MASK
      routes:
      - to: default
        via: $GW
      nameservers:
        addresses: [$DNS]
  version: 2
EOF


# Aplicar la configuración
sudo netplan apply

# Mostrar la configuración aplicada
echo -e "\n=== Configuración aplicada ==="
ip addr show dev $IFACE
ip route | grep default
cat /etc/netplan/50-cloud-init.yaml
